url: http://crdx.org
domain: crdx.org
title: crdx.org
permalink: /:year/:month/:day/:title/
paginate: 10
destination: _site/htdocs
markdown: kramdown
lsi: false
future: false
relative_permalinks: true

exclude: [
            "README.md",
            "Gruntfile.coffee",
            "package.json",
            "node_modules",
            "open.bat",
            "phpstorm.bat",
            "deploy-*",
            "LICENCE.md"
         ]

jekyll_sort:
    - src: posts
      by: date
      direction: down
      dest: posts_sorted
#    - src: tags
#      by: 0
#      direction: up
#      dest: tags_sorted