url:          "http://crdx.org"
domain:       "crdx.org"
title:        "crdx.org"

permalink:    "/:year/:month/:day/:title.html"
paginate:     10
destination:  "../dist/deploy"
pygments:     true
markdown:     "rdiscount"
lsi:          false
future:       false

exclude:      ["README.md", "Gruntfile.js", "package.json", "node_modules"]